### PR TITLE
Fixes #61 by restoring terminal on exit

### LINKED ISSUE #61: Terminal disfunction when exiting client
Hey,

When I use the client, each time I quit (Ctrl + Q) my terminal is behaving very weird. Here is how it looks when I try `ls`:

I'm not sure what is causing it, maybe SIGWINCH..

Tried with and without tmux, bash and zsh

Any ideas?

### PR DESCRIPTION
**Pull request by Sh4d1**
Use of moby/pkg/term to set to raw terminal and restore after

May need some tests on Windows and Mac?

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

**Comment by moul** [comment]
Thank you, I think that this PR fixes #61 but introduce duplicate code with the existing terminal set raw mode used from the ssh package

If moby’s works better than the original one, we should safely only keep the good one

**Comment by Sh4d1** [comment]
Hmm my bad I did not notice this package was used. I'll try without this evening or tomorrow :)

**Comment by Sh4d1** [comment]
@moul so It works when replacing ssh terminal package. I moved it to the main Loop, I was not sure what changes if it was in the writeloop or the main one though.

**Comment by Sh4d1** [comment]
@moul seems good to you? Or are some tests needed?

**Comment by moul** [comment]
tested and approved :)

**Pull request merged**
